version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.23.1

workflows:
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish-dev:
          orb-name: prometheus/prometheus
          publish-token-variable: CIRCLECI_API_TOKEN
          requires:
          - orb-tools/lint
          - orb-tools/pack
          filters:
            branches:
              only: master
      - orb-tools/publish:
          orb-ref: prometheus/prometheus@$CIRCLE_TAG
          publish-token-variable: CIRCLECI_API_TOKEN
          checkout: false
          attach-workspace: true
          requires:
          - orb-tools/pack
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
