description: >
  Setup the environment for building the container images.

steps:
- setup_environment
- setup_remote_docker:
    version: 18.06.0-ce
- run: docker run --privileged linuxkit/binfmt:v0.6
- attach_workspace:
    at: .
