description: >
  Cross-build and store the binaries.

machine:
  image: ubuntu-2004:202111-02

parameters:
  parallelism:
    type: integer
    description: The number of builds to run in parallel.
    default: 3
  promu_opts:
    type: string
    description: Additional promu options.
    default: ""

parallelism: << parameters.parallelism >>

steps:
- setup_environment
- run: promu crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX << parameters.promu_opts >>
- persist_to_workspace:
    root: .
    paths:
    - .build
- store_artifacts:
    path: .build
    destination: /build
